# Multiple Linear Regression - Çoklu Doğrusal Regresyon
- Temel amaç, bağımlı ve bağımsız değişkenler arasındaki ilişkiyi ifade eden doğrusal fonksiyonu bulmaktır

- Yi = b0 + b1Xi1 + b2Xi2 + ...... + bjXij + ...... + bpXip + £i
- b0,b1,b2,...,bj,bp bağımsız değişkenlerin katsayılarıdır.
- Bu katsayılar ile model içindeki  bağımsız değişkenlerin etkilerini kontrol etmek için kullanılır.
- Yani bağımsız değişkenlerin katsayılarını bulmaya çalışacaz.
- Y Bağımlı Değişken 
- X Bağımsız Değişken

# MODEL OLUŞTURMA

In [1]:
import pandas as pd
df = pd.read_csv("./Advertising.csv")
df = df.iloc[:,1:len(df)] 
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [2]:
X= df.drop("Sales", axis = 1)
y= df[["Sales"]]

In [3]:
# Bağımlı Değişken 
y.head()

Sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [4]:
# Bağımsız Değişken
X.head()

TV  Radio  Newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [5]:
# Statsmodel ile Model Kurma

In [6]:
import statsmodels.api as sm

In [7]:
# Linear Model(lm) dir. OLS ise regression modelini kurmak için oluşturulan bi fonksiyon.
lm = sm.OLS(y,X)

In [8]:
statsModel = lm.fit()

In [10]:
statsModel.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  Sales   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              3566.
Date:                Sat, 20 Feb 2021   Prob (F-statistic):                   2.43e-171
Time:                        13:29:46   Log-Likelihood:                         -423.54
No. Observations:                 200   AIC:                                      853.1
Df Residuals:                     197   BIC:                                      863.0
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0538      0.001     40.507      0.000       0.051       0.056
Radio          0.2222      0.009     23.595      0.000       0.204       0.241
Newspaper      0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [11]:
#Scikitlearn ile Model Kurmak 

In [12]:
from sklearn.linear_model import LinearRegression 
# Linear Model(lm) dir
lm = LinearRegression()

In [13]:
# sklearn den fit edip modelimizi kurduk.
scikitModel = lm.fit(X,y)

In [14]:
# Sabit Değer
scikitModel.intercept_

array([2.93888937])

In [15]:
# bağımsız değişkenlerine ilişkin katsayılar. 3 tane Bağımsız değişken(X) vardır bunlar; TV,Radio,Newspaper
scikitModel.coef_

array([[ 0.04576465,  0.18853002, -0.00103749]])

# TAHMİN İŞLEMLERİ

- **Sales = 2.93888937 + TV * 0.04576465 + radio * 0.18853002 - newspaper * 0.00103749**
- Eğer 30 birim TV , 10 birim radio, 40 birim newspaper harcaması olursa bu durumda satışlar ne olur?

In [16]:
TV = 30
radio = 10
newspaper = 40

harcama = 2.93888937 + TV * 0.04576465 + radio * 0.18853002 - newspaper * 0.00103749

In [17]:
harcama

6.15562947

In [18]:
yeni_veri = [[30],[10],[40]]

In [19]:
# T ile transpozunu almış olduk.
import pandas as pd
yeni_veri = pd.DataFrame(yeni_veri).T

In [20]:
yeni_veri.columns = ["TV","radio","newspaper"]

In [22]:
# Burada TV Radio ve newspaper ın bağımsız değişken değerini tabloda göstermiş olduk.
yeni_veri

TV  radio  newspaper
0  30     10         40

In [23]:
tahmin = scikitModel.predict(yeni_veri)
tahmin

array([[6.15562918]])

In [24]:
# scikit learnden hata kareler ortalamasını(mean_squared_error) impor ettik.
from sklearn.metrics import mean_squared_error

In [25]:
# Gerçek değerler
y.head()

Sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [26]:
# X_tahmin baapımsız değişken deperlerinin tahminleri aslında ^y değeridir.
X_tahmin = scikitModel.predict(X)[0:10]
X_tahmin

array([[20.52397441],
       [12.33785482],
       [12.30767078],
       [17.59782951],
       [13.18867186],
       [12.47834763],
       [11.72975995],
       [12.12295317],
       [ 3.72734086],
       [12.55084872]])

In [27]:
# MSE = hata kareler ortalaması
MSE = mean_squared_error(y, scikitModel.predict(X))
MSE

2.784126314510936

In [28]:
# RMSE = Hata kareler ortalmasının karekökü  
import numpy as np
RMSE = np.sqrt(MSE)
RMSE

1.6685701407225697

# MODEL TUNİNG - MODEL DOĞRULAMA

In [29]:
X.head()

TV  Radio  Newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [30]:
y.head()

Sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [39]:
# Sınama Seti = train_test_split
from sklearn.model_selection import train_test_split

In [32]:
# buradaki 0.20 ise yüzdelik olara bakarsak %80 i train %20 ise test olarak palaştırmış oluyoruz.
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.20, random_state = 99)

In [35]:
# train setinin bağımsız değişkeni
X_train.head()

TV  Radio  Newspaper
16    67.8   36.6      114.0
51   100.4    9.6        3.6
97   184.9   21.0       22.0
164  117.2   14.7        5.4
71   109.8   14.3       31.7

In [36]:
# train setinin bağımlı değişkeni
y_train.head()

Sales
16    12.5
51    10.7
97    15.5
164   11.9
71    12.4

In [37]:
# test setinin bağımsız değişkeni
X_test.head()

TV  Radio  Newspaper
135  48.3   47.0        8.5
127  80.2    0.0        9.2
191  75.5   10.8        6.0
66   31.5   24.6        2.2
119  19.4   16.0       22.3

In [38]:
# test setinin bağımlı değişkeni
y_test.head()

Sales
135   11.6
127    8.8
191    9.9
66     9.5
119    6.6

In [40]:
lm = LinearRegression()
model = lm.fit(X_train,y_train)

In [42]:
# Eğitim(train) hatası
np.sqrt(mean_squared_error(y_train, model.predict(X_train)))

1.7236824822650751

In [43]:
# Test Hatası
np.sqrt(mean_squared_error(y_test, model.predict(X_test)))

1.4312783138301641

In [44]:
# k-katlı cv (cross-validation = çapraz doğrulama) yöntemi doğrulanmış bir hata verir.
from sklearn.model_selection import cross_val_score

In [45]:
cross_val_score(model,X_train,y_train, cv=10, scoring= "neg_mean_squared_error")

array([-2.1019073 , -2.48953197, -3.09704214, -2.34694216, -3.68175761,
       -1.8691401 , -3.18173007, -4.1927349 , -2.17128376, -8.03821974])

In [49]:
# cv elde eldilmiş MSE(yani hatalar karesinin ortamalaması.) değeridir. 
np.mean(-cross_val_score(model,X_train,y_train, cv=10, scoring= "neg_mean_squared_error"))

3.317028974234127

In [50]:
# cv elde eldilmiş RMSE(Yani hatalar karesinin ortalamasının karekökü) değeridir. 
np.sqrt(np.mean(-cross_val_score(model,X_train,y_train, cv=10, scoring= "neg_mean_squared_error")))

1.821271252239525